import { randomUUID } from 'node:crypto';
import { createReadStream, ReadStream } from 'node:fs';
import { access, mkdir, readdir, rm, rmdir, writeFile } from 'node:fs/promises';
import { dirname, extname, join, resolve } from 'node:path';
import { BadRequestException, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

/** Matches a UUID as generated by Prisma's `@default(uuid())` — the only shape a meetingId is ever expected to have. */
const MEETING_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface StorageFileInput {
  originalFilename: string;
  buffer: Buffer;
}

export interface StorageByteRange {
  start: number;
  end: number;
}

@Injectable()
export class StorageService {
  private readonly uploadsDir: string;

  constructor(config: ConfigService) {
    this.uploadsDir = resolve(config.getOrThrow<string>('UPLOADS_DIR'));
  }

  async save(meetingId: string, file: StorageFileInput): Promise<string> {
    const dir = this.resolveMeetingDir(meetingId);
    await mkdir(dir, { recursive: true });
    const storagePath = join(dir, this.generateFilename(file.originalFilename));
    await writeFile(storagePath, file.buffer);
    return storagePath;
  }

  /**
   * The `{UPLOADS_DIR}/{meetingId}` directory a recording for this meeting is stored under.
   * Rejects anything that isn't a plain UUID — `meetingId` can come straight from a URL
   * param, and without this check a value like `..\..\Temp` would resolve outside
   * `UPLOADS_DIR` via `path.join`'s normal `..` handling.
   */
  resolveMeetingDir(meetingId: string): string {
    if (!MEETING_ID_PATTERN.test(meetingId)) {
      throw new BadRequestException('Invalid meeting id');
    }
    return join(this.uploadsDir, meetingId);
  }

  /** A fresh `{uuid}{ext}` filename, extension derived from the given original filename. */
  generateFilename(originalFilename: string): string {
    return `${randomUUID()}${extname(originalFilename)}`;
  }

  createReadStream(storagePath: string, range?: StorageByteRange): ReadStream {
    return createReadStream(storagePath, range);
  }

  async delete(storagePath: string): Promise<void> {
    await rm(storagePath, { force: true });

    try {
      await rmdir(dirname(storagePath));
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== 'ENOTEMPTY' && code !== 'ENOENT') {
        throw err;
      }
    }
  }

  /**
   * Removes every file in `{UPLOADS_DIR}/{meetingId}` except `keepStoragePath`.
   * Used to clean up losing writes from concurrent uploads to the same meeting:
   * unlike deleting a single previously-known path, this is based on the actual
   * directory contents after the DB row is committed, so it's race-free —
   * whichever upload's row won the DB upsert is also the one whose file survives.
   * Best-effort: a failure to remove one stray file doesn't fail the others or throw.
   */
  async pruneMeetingDir(
    meetingId: string,
    keepStoragePath: string,
  ): Promise<void> {
    const dir = this.resolveMeetingDir(meetingId);
    let entries: string[];
    try {
      entries = await readdir(dir);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        return;
      }
      throw err;
    }

    await Promise.allSettled(
      entries
        .map((entry) => join(dir, entry))
        .filter((entryPath) => entryPath !== keepStoragePath)
        .map((entryPath) => rm(entryPath, { force: true })),
    );
  }

  async exists(storagePath: string): Promise<boolean> {
    try {
      await access(storagePath);
      return true;
    } catch {
      return false;
    }
  }
}
