import { randomUUID } from 'node:crypto';
import { createReadStream, ReadStream } from 'node:fs';
import { access, mkdir, readdir, rm, rmdir, writeFile } from 'node:fs/promises';
import { dirname, extname, join, resolve } from 'node:path';
import { BadRequestException, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

/** Matches a UUID as generated by Prisma's `@default(uuid())` — the only shape a meetingId or userId is ever expected to have. */
const ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface StorageFileInput {
  originalFilename: string;
  buffer: Buffer;
}

export interface StorageByteRange {
  start: number;
  end: number;
}

@Injectable()
export class StorageService {
  private readonly uploadsDir: string;

  constructor(config: ConfigService) {
    this.uploadsDir = resolve(config.getOrThrow<string>('UPLOADS_DIR'));
  }

  async save(meetingId: string, file: StorageFileInput): Promise<string> {
    const dir = this.resolveMeetingDir(meetingId);
    await mkdir(dir, { recursive: true });
    const storagePath = join(dir, this.generateFilename(file.originalFilename));
    await writeFile(storagePath, file.buffer);
    return storagePath;
  }

  /**
   * The `{UPLOADS_DIR}/{meetingId}` directory a recording for this meeting is stored under.
   * Rejects anything that isn't a plain UUID — `meetingId` can come straight from a URL
   * param, and without this check a value like `..\..\Temp` would resolve outside
   * `UPLOADS_DIR` via `path.join`'s normal `..` handling.
   */
  resolveMeetingDir(meetingId: string): string {
    this.assertValidId(meetingId, 'meeting');
    return join(this.uploadsDir, meetingId);
  }

  /**
   * The `{UPLOADS_DIR}/avatars/{userId}` directory an avatar for this user is stored under.
   * Namespaced under `avatars/` (unlike a meeting recording's directory, which sits directly
   * under `UPLOADS_DIR`) so a meeting id and a user id can never resolve to the same path.
   * Rejects anything that isn't a plain UUID for the same path-traversal reason as
   * `resolveMeetingDir` — `userId` can come straight from a JWT payload.
   */
  resolveAvatarDir(userId: string): string {
    this.assertValidId(userId, 'user');
    return join(this.uploadsDir, 'avatars', userId);
  }

  /**
   * Shared UUID-shape guard behind both `resolve*Dir` methods — the only thing standing
   * between an id-shaped URL/token param and a `path.join` that escapes `UPLOADS_DIR`.
   */
  private assertValidId(id: string, kind: 'meeting' | 'user'): void {
    if (!ID_PATTERN.test(id)) {
      throw new BadRequestException(`Invalid ${kind} id`);
    }
  }

  /** A fresh `{uuid}{ext}` filename, extension derived from the given original filename. */
  generateFilename(originalFilename: string): string {
    return `${randomUUID()}${extname(originalFilename)}`;
  }

  createReadStream(storagePath: string, range?: StorageByteRange): ReadStream {
    return createReadStream(storagePath, range);
  }

  async delete(storagePath: string): Promise<void> {
    await rm(storagePath, { force: true });

    try {
      await rmdir(dirname(storagePath));
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code !== 'ENOTEMPTY' && code !== 'ENOENT') {
        throw err;
      }
    }
  }

  /**
   * Removes every file in `{UPLOADS_DIR}/{meetingId}` except `keepStoragePath`.
   * Used to clean up losing writes from concurrent uploads to the same meeting:
   * unlike deleting a single previously-known path, this is based on the actual
   * directory contents after the DB row is committed, so it's race-free —
   * whichever upload's row won the DB upsert is also the one whose file survives.
   * Best-effort: a failure to remove one stray file doesn't fail the others or throw.
   */
  pruneMeetingDir(meetingId: string, keepStoragePath: string): Promise<void> {
    return this.pruneDir(this.resolveMeetingDir(meetingId), keepStoragePath);
  }

  /**
   * Removes every file in `{UPLOADS_DIR}/avatars/{userId}` except
   * `keepStoragePath`, for the same reason and in the same race-free way as
   * `pruneMeetingDir` — see that method's doc comment.
   */
  pruneAvatarDir(userId: string, keepStoragePath: string): Promise<void> {
    return this.pruneDir(this.resolveAvatarDir(userId), keepStoragePath);
  }

  private async pruneDir(dir: string, keepStoragePath: string): Promise<void> {
    let entries: string[];
    try {
      entries = await readdir(dir);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        return;
      }
      throw err;
    }

    await Promise.allSettled(
      entries
        .map((entry) => join(dir, entry))
        .filter((entryPath) => entryPath !== keepStoragePath)
        .map((entryPath) => rm(entryPath, { force: true })),
    );
  }

  async exists(storagePath: string): Promise<boolean> {
    try {
      await access(storagePath);
      return true;
    } catch {
      return false;
    }
  }
}
